#!/bin/sh
#npm run build
echo "CONTACT_EMAIL=\"$CONTACT_EMAIL\"" >>.env
echo "SITE_NAME=\"$SITE_NAME\"" >>.env
echo "DEFAULT_DOMAIN=\"$DEFAULT_DOMAIN\"" >>.env
echo "RECAPTCHA_SITE_KEY=\"$RECAPTCHA_SITE_KEY\"" >>.env
echo "GOOGLE_ANALYTICS=\"$GOOGLE_ANALYTICS\"" >>.env
echo "REPORT_EMAIL=\"$REPORT_EMAIL\"" >>.env
echo "DISALLOW_ANONYMOUS_LINKS=\"$DISALLOW_ANONYMOUS_LINKS\"" >>.env
echo "DISALLOW_REGISTRATION=\"$DISALLOW_REGISTRATION\"" >>.env
echo "DISALLOW_CUSTOMDOMAINS=\"$DISALLOW_CUSTOMDOMAINS\"" >>.env
echo "=SENTRY_PUBLIC_DSN\"$SENTRY_PUBLIC_DSN\"" >>.env
exec npm start
